# Generated by Django 3.0.8 on 2021-06-30 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20210630_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
