# Generated by Django 3.0.8 on 2021-07-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20210705_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='course',
            field=models.ManyToManyField(related_name='course', to='calendarapp.Course'),
        ),
    ]
