# Generated by Django 3.0.8 on 2021-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20210705_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
