# Generated by Django 3.0.8 on 2021-07-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20210705_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='calendarapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=15)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Professor')),
            ],
        ),
    ]
