# Generated by Django 3.0.8 on 2021-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20210706_1151'),
        ('calendarapp', '0007_auto_20210705_1606'),
    ]

    operations = [
    ]
