# Generated by Django 3.0.8 on 2021-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_merge_20210706_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayavailability',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=15),
        ),
    ]
