# Generated by Django 3.0.8 on 2021-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_auto_20210706_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='rank',
            field=models.CharField(choices=[('1', 'Rank 1'), ('2', 'Rank 2'), ('3', 'Rank 3')], default='1', max_length=6),
        ),
    ]
