# Generated by Django 3.0.8 on 2021-07-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_auto_20210708_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday')], max_length=15)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Professor')),
            ],
        ),
    ]
