# Generated by Django 3.0.8 on 2021-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_auto_20210718_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
