# Generated by Django 3.0.8 on 2021-07-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0018_auto_20210727_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Venue'),
        ),
    ]
